{% set name = "waves" %}
{% set version = "0.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl-aea/waves/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3868f1592a21e4b671ed31e66951151d73ff0535e0209c9621629994b25c0cd4

build:
  noarch: python
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - odb_extract = waves._abaqus.odb_extract:main
    - waves = waves._main:main

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - pip
    - scons >=4.6
    - setuptools >=64
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx-book-theme
    - sphinx-design
    - sphinxcontrib-bibtex
  run:
    - python >={{ python_min }}
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons >=4
    - xarray

test:
  requires:
    - pip
    - pytest>=6
    - pytest-xdist
    - python {{ python_min }}
  imports:
    - waves

about:
  home: https://github.com/lanl-aea/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Computational science and engineering parameteric study workflows'
  description: |
    WAVES (LANL code C23004) is a computational science and engineering workflow tool that integrates parametric studies
    with traditional software build systems.
  doc_url: https://lanl-aea.github.io/waves/index.html
  dev_url: https://github.com/lanl-aea/waves

extra:
  recipe-maintainers:
    - Prabhu-LANL
    - kbrindley
