{% set name = "waves" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl-aea/waves/archive/refs/tags/{{ version }}.tar.gz
  sha256: d14af9a93c12d2e84a3b67345b2ec5829a202a01b5fb10b1eb0a9dbda4018322

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - odb_extract = waves._abaqus.odb_extract:main
    - waves = waves._main:main
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - scons >=4
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
    - setuptools_scm >=8
  host:
    - python
    - python-build
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >=3.8
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons
    - xarray

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - waves

about:
  home: https://github.com/lanl-aea/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Parameteric study computational engineering workflow tool
  description: |
    WAVES (LANL code C23004) is a computational engineering workflow tool that integrates parametric studies with
    traditional software build systems.
  doc_url: https://lanl-aea.github.io/waves/index.html
  dev_url: https://github.com/lanl-aea/waves

extra:
  recipe-maintainers:
    - Prabhu-LANL
    - kbrindley
