{% set name = "waves" %}
{% set version = "0.13.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl-aea/waves/archive/refs/tags/{{ version }}.tar.gz
  sha256: b70c2d57f552d5189ca5ef9c88a3c59c5765285a27bfbf783de2d5907636fb56

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - scons install --prefix=${PREFIX}  # [unix]
    - scons install --prefix=%PREFIX%  # [win]
  entry_points:
    - odb_extract = waves._abaqus.odb_extract:main
    - waves = waves._main:main

requirements:
  host:
    - python {{ python_min }}
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pip
    - python-build
    - pyyaml
    - salib >=1.4.6
    - scipy >=1.7
    - scons >=4.6
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinx-copybutton >=0.5.1
    - sphinx-design
    - sphinxcontrib-bibtex
    - xarray >=2024.10.0
  run:
    - python >={{ python_min }}
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1.4.6
    - scipy >=1.7
    - scons >=4
    - xarray >=2024.10.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=6
    - pytest-xdist
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinxcontrib-bibtex
  imports:
    - waves

about:
  home: https://github.com/lanl-aea/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Computational science and engineering parameteric study workflows'
  description: |
    WAVES (LANL code C23004) is a computational science and engineering workflow tool that integrates parametric studies
    with traditional software build systems.
  doc_url: https://lanl-aea.github.io/waves/index.html
  dev_url: https://github.com/lanl-aea/waves

extra:
  recipe-maintainers:
    - Prabhu-LANL
    - kbrindley
